/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class AdminUsersFrame extends javax.swing.JFrame {

    String currentEmail;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminUsersFrame.class.getName());

    /**
     * Creates new form AdminUsersFrame
     */
    public AdminUsersFrame(String email) {
        initComponents();
        this.currentEmail = email;
        loadUsers("all");
    }

    public void loadUsers(String type) {
        try {

            ResultSet rs;

            if (type.equals("pending")) {
                rs = dao.UserDAO.getPendingUsers();
            } else {
                rs = dao.UserDAO.getAllUsers();
            }

            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) usersTable.getModel();

            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("user_id"),
                    rs.getString("name"),
                    rs.getString("email"),
                    rs.getString("phone"),
                    rs.getString("role"),
                    rs.getString("approval_status") + " / "
                    + (rs.getInt("is_active") == 1 ? "Active" : "Inactive"),
                    rs.getTimestamp("created_at")
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        showPendingBtn = new javax.swing.JButton();
        showAllBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        approveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        changePasswordBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText(" Users");

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Phone", "Role", "Status", "Created At"
            }
        ));
        jScrollPane1.setViewportView(usersTable);

        showPendingBtn.setText("Show pending users");
        showPendingBtn.addActionListener(this::showPendingBtnActionPerformed);

        showAllBtn.setText("Show all users");
        showAllBtn.addActionListener(this::showAllBtnActionPerformed);

        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);

        approveBtn.setText("Approve");
        approveBtn.addActionListener(this::approveBtnActionPerformed);

        updateBtn.setText("Update");
        updateBtn.addActionListener(this::updateBtnActionPerformed);

        changePasswordBtn.setText("Change password");
        changePasswordBtn.addActionListener(this::changePasswordBtnActionPerformed);

        deleteBtn.setText("Delete User");
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);

        searchBtn.setText("Search");
        searchBtn.addActionListener(this::searchBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(approveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(searchField)
                                .addGap(18, 18, 18)
                                .addComponent(showPendingBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(searchBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(changePasswordBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(showAllBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(showPendingBtn)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAllBtn)
                    .addComponent(approveBtn)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(changePasswordBtn)
                    .addComponent(deleteBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showPendingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPendingBtnActionPerformed
        // TODO add your handling code here:
        loadUsers("pending");
    }//GEN-LAST:event_showPendingBtnActionPerformed

    private void showAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllBtnActionPerformed
        // TODO add your handling code here:
        loadUsers("all");
    }//GEN-LAST:event_showAllBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new AdminDashboard(currentEmail).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backBtnActionPerformed

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        // TODO add your handling code here:
        int row = usersTable.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a user first");
            return;
        }

        int userId = Integer.parseInt(usersTable.getValueAt(row, 0).toString());

// 🔥 FIXED COLUMN INDEX
        String status = usersTable.getValueAt(row, 5).toString();

        if (!status.toLowerCase().contains("pending")) {
            JOptionPane.showMessageDialog(this, "User is not pending");
            return;
        }

        dao.UserDAO.approveUser(userId);

        JOptionPane.showMessageDialog(this, "User Approved");

        loadUsers("pending");
    }//GEN-LAST:event_approveBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int row = usersTable.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select user first");
            return;
        }

        int userId = Integer.parseInt(usersTable.getValueAt(row, 0).toString());

        String currentName = usersTable.getValueAt(row, 1).toString();
        String currentPhone = usersTable.getValueAt(row, 3).toString();

        String newName = JOptionPane.showInputDialog(this, "Enter new name", currentName);
        String newPhone = JOptionPane.showInputDialog(this, "Enter new phone", currentPhone);

        if (newName == null || newPhone == null) {
            return;
        }

        // validation
        if (!newName.matches("[A-Za-z ]+")) {
            JOptionPane.showMessageDialog(this, "Invalid name");
            return;
        }

        if (!newPhone.matches("\\d{10}")) {
            JOptionPane.showMessageDialog(this, "Invalid phone");
            return;
        }

        dao.UserDAO.updateUser(userId, newName, newPhone);

        JOptionPane.showMessageDialog(this, "User Updated");

        loadUsers("all");
    }//GEN-LAST:event_updateBtnActionPerformed

    private void changePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordBtnActionPerformed
        // TODO add your handling code here:
        int row = usersTable.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select user first");
            return;
        }

        int userId = Integer.parseInt(usersTable.getValueAt(row, 0).toString());

        String newPassword = JOptionPane.showInputDialog(this, "Enter new password");

        if (newPassword == null) {
            return;
        }

        if (newPassword.length() < 6) {
            JOptionPane.showMessageDialog(this, "Password must be at least 6 characters");
            return;
        }

        dao.UserDAO.updatePassword(userId, newPassword);

        JOptionPane.showMessageDialog(this, "Password Updated");
    }//GEN-LAST:event_changePasswordBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:

        int row = usersTable.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select user first");
            return;
        }

        int userId = Integer.parseInt(usersTable.getValueAt(row, 0).toString());

        int confirm = JOptionPane.showConfirmDialog(this, "Deactivate this user?", "Confirm", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            dao.UserDAO.deactivateUser(userId);

            JOptionPane.showMessageDialog(this, "User Deactivated");

            loadUsers("all");
        }

    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
  

    String keyword = searchField.getText().trim();

    try {
        ResultSet rs;

        // 🔥 KEY LOGIC
        if(keyword.isEmpty()) {
            rs = dao.UserDAO.getAllUsers();   // show all
        } else {
            rs = dao.UserDAO.searchUsers(keyword); // search
        }

        DefaultTableModel model =
            (DefaultTableModel) usersTable.getModel();

        model.setRowCount(0);

        while(rs.next()) {

            String status =
                rs.getString("approval_status") + " / " +
                (rs.getInt("is_active") == 1 ? "Active" : "Inactive");

            model.addRow(new Object[]{
                rs.getInt("user_id"),
                rs.getString("name"),
                rs.getString("email"),
                rs.getString("phone"),
                rs.getString("role"),
                status,
                rs.getTimestamp("created_at")
            });
        }

    } catch(Exception e) {
        e.printStackTrace();
    }

    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminUsersFrame("admin@gmail.com").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton changePasswordBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton showAllBtn;
    private javax.swing.JButton showPendingBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
