/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Hp
 */
public class AdminStaffFrame extends javax.swing.JFrame {
    String currentEmail;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminStaffFrame.class.getName());

    /**
     * Creates new form AdminStaffFrame
     */
    public AdminStaffFrame(String email) {
    initComponents();
    loadStaff();
}
    
    public void loadStaff() {
    try {
        java.sql.ResultSet rs = dao.UserDAO.getAllStaff();

        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) staffTable.getModel();

        model.setRowCount(0);

        while(rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("staff_id"),
                rs.getString("name"),
                rs.getString("role"),
                rs.getString("phone"),
                rs.getString("shift"),
                rs.getDouble("salary"),
                rs.getDate("joining_date")
            });
        }

    } catch(Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        staffTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        updateStaffBtn = new javax.swing.JButton();
        deleteStaffBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Staff Details");

        staffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Role", "Phone", "Shift", "Salary", "Joining Date"
            }
        ));
        jScrollPane1.setViewportView(staffTable);

        jButton1.setText("Back");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Add Staff");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        updateStaffBtn.setText("Update");
        updateStaffBtn.addActionListener(this::updateStaffBtnActionPerformed);

        deleteStaffBtn.setText("Delete");
        deleteStaffBtn.addActionListener(this::deleteStaffBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateStaffBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteStaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateStaffBtn)
                    .addComponent(deleteStaffBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new AdminDashboard(currentEmail).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new AddStaffFrame(currentEmail).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStaffBtnActionPerformed
        // TODO add your handling code here:

    int row = staffTable.getSelectedRow();

    if(row == -1) {
        JOptionPane.showMessageDialog(this, "Select staff first");
        return;
    }

    int staffId = Integer.parseInt(staffTable.getValueAt(row, 0).toString());

    String name = JOptionPane.showInputDialog(this, "Name", staffTable.getValueAt(row, 1));
    String role = JOptionPane.showInputDialog(this, "Role", staffTable.getValueAt(row, 2));
    String phone = JOptionPane.showInputDialog(this, "Phone", staffTable.getValueAt(row, 3));
    String shift = JOptionPane.showInputDialog(this, "Shift", staffTable.getValueAt(row, 4));
    String salaryStr = JOptionPane.showInputDialog(this, "Salary", staffTable.getValueAt(row, 5));

    if(name == null || role == null || phone == null || shift == null || salaryStr == null) return;

    double salary;

    try {
        salary = Double.parseDouble(salaryStr);
    } catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Invalid salary");
        return;
    }

    dao.UserDAO.updateStaff(staffId, name, role, phone, shift, salary);

    JOptionPane.showMessageDialog(this, "Staff Updated");

    loadStaff();

    }//GEN-LAST:event_updateStaffBtnActionPerformed

    private void deleteStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStaffBtnActionPerformed
        // TODO add your handling code here:
       int row = staffTable.getSelectedRow();

    if(row == -1) {
        JOptionPane.showMessageDialog(this, "Select staff first");
        return;
    }

    int staffId = Integer.parseInt(staffTable.getValueAt(row, 0).toString());

    int confirm = JOptionPane.showConfirmDialog(this, "Delete this staff?", "Confirm", JOptionPane.YES_NO_OPTION);

    if(confirm == JOptionPane.YES_OPTION) {

        dao.UserDAO.deleteStaff(staffId);

        JOptionPane.showMessageDialog(this, "Staff Deleted");

        loadStaff();
    }

    }//GEN-LAST:event_deleteStaffBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminStaffFrame("admin@gmail.com").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteStaffBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable staffTable;
    private javax.swing.JButton updateStaffBtn;
    // End of variables declaration//GEN-END:variables
}
