/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class AdminFlatsFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminFlatsFrame.class.getName());

    /**
     * Creates new form AdminFlatsFrame
     */
    String currentEmail;

public AdminFlatsFrame(String email) {
    initComponents();
    this.currentEmail = email;
    loadFlats();
}
    
    public void loadFlats() {
    try {
        ResultSet rs = dao.UserDAO.getFlatDetails();

        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) flatsTable.getModel();

        model.setRowCount(0);

        while(rs.next()) {

            String user = rs.getString("name");

            model.addRow(new Object[]{
                rs.getInt("flat_id"),
                rs.getString("block"),
                rs.getString("flat_number"),
                rs.getInt("floor"),
                user == null ? "-" : user,
                rs.getString("type") == null ? "-" : rs.getString("type"),
                rs.getDate("start_date") == null ? "-" : rs.getDate("start_date")
            });
        }

    } catch(Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flatsTable = new javax.swing.JTable();
        assignFlatBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        updateFlatBtn = new javax.swing.JButton();
        deleteFlatBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Flat details");

        flatsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Block", "Flat No", "Floor", "User", "Type", "Start Date"
            }
        ));
        jScrollPane1.setViewportView(flatsTable);

        assignFlatBtn.setText("Assign Flat");
        assignFlatBtn.addActionListener(this::assignFlatBtnActionPerformed);

        jButton1.setText("Add Flat");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);

        updateFlatBtn.setText("Update Flat");
        updateFlatBtn.addActionListener(this::updateFlatBtnActionPerformed);

        deleteFlatBtn.setText("Delete Flat");
        deleteFlatBtn.addActionListener(this::deleteFlatBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assignFlatBtn)
                                .addGap(58, 58, 58)
                                .addComponent(updateFlatBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addGap(85, 85, 85)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteFlatBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(jLabel1)
                    .addComponent(deleteFlatBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignFlatBtn)
                    .addComponent(jButton1)
                    .addComponent(updateFlatBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assignFlatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignFlatBtnActionPerformed
        // TODO add your handling code here:
        new AssignFlatFrame(currentEmail).setVisible(true);
this.dispose();
    }//GEN-LAST:event_assignFlatBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new AddFlatFrame(currentEmail).setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
    new AdminDashboard(currentEmail).setVisible(true);
    this.dispose();

    }//GEN-LAST:event_backBtnActionPerformed

    private void updateFlatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFlatBtnActionPerformed
        // TODO add your handling code here:      
    int row = flatsTable.getSelectedRow();

    if(row == -1) {
        JOptionPane.showMessageDialog(this, "Select a flat first");
        return;
    }

    int flatId = Integer.parseInt(flatsTable.getValueAt(row, 0).toString());

    String currentBlock = flatsTable.getValueAt(row, 1).toString();
    String currentFlatNo = flatsTable.getValueAt(row, 2).toString();
    int currentFloor = Integer.parseInt(flatsTable.getValueAt(row, 3).toString());

    String newBlock = JOptionPane.showInputDialog(this, "Enter block", currentBlock);
    String newFlatNo = JOptionPane.showInputDialog(this, "Enter flat number", currentFlatNo);
    String floorStr = JOptionPane.showInputDialog(this, "Enter floor", currentFloor);

    if(newBlock == null || newFlatNo == null || floorStr == null) return;

    int newFloor;

    try {
        newFloor = Integer.parseInt(floorStr);
    } catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Invalid floor");
        return;
    }

    boolean success = dao.UserDAO.updateFlat(flatId, newBlock, newFlatNo, newFloor);

if(success) {
    JOptionPane.showMessageDialog(this, "Flat Updated");
    loadFlats();
} else {
    JOptionPane.showMessageDialog(this, "Flat already exists in this block");
}

    loadFlats(); // refresh table

     
    }//GEN-LAST:event_updateFlatBtnActionPerformed

    private void deleteFlatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFlatBtnActionPerformed
        // TODO add your handling code here:

    int row = flatsTable.getSelectedRow();

    if(row == -1) {
        JOptionPane.showMessageDialog(this, "Select a flat first");
        return;
    }

    int flatId = Integer.parseInt(flatsTable.getValueAt(row, 0).toString());

    int confirm = JOptionPane.showConfirmDialog(this, "Delete this flat?", "Confirm", JOptionPane.YES_NO_OPTION);

    if(confirm == JOptionPane.YES_OPTION) {

        boolean success = dao.UserDAO.deleteFlat(flatId);

        if(success) {
            JOptionPane.showMessageDialog(this, "Flat Deleted");
            loadFlats();
        } else {
            JOptionPane.showMessageDialog(this, "Flat is currently assigned, cannot delete");
        }
    }

    }//GEN-LAST:event_deleteFlatBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminFlatsFrame("admin@gmail.com").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignFlatBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteFlatBtn;
    private javax.swing.JTable flatsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateFlatBtn;
    // End of variables declaration//GEN-END:variables
}
