/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class MyComplaintsFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MyComplaintsFrame.class.getName());

    /**
     * Creates new form MyComplaintsFrame
     */
    public MyComplaintsFrame() {
        initComponents();
    }

    String currentEmail;

    public MyComplaintsFrame(String email) {
        initComponents();
        this.currentEmail = email;

        loadComplaints(email);
    }

    public void loadComplaints(String email) {
        try {
            ResultSet rs = dao.UserDAO.getComplaints(email);

            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) complaintTable.getModel();

            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
    rs.getInt("complaint_id"),   // 🔥 ADD THIS
    rs.getString("description"),
    rs.getString("priority"),
    rs.getString("status"),
    rs.getDate("date_created")
});
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        complaintTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        addComplaintBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        deleteComplaintBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        complaintTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Description", "Priority", "Status", "Date"
            }
        ));
        jScrollPane1.setViewportView(complaintTable);

        jLabel1.setText("My Complaints");

        addComplaintBtn.setText("Add Complaint");
        addComplaintBtn.addActionListener(this::addComplaintBtnActionPerformed);

        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);

        deleteComplaintBtn.setText("Delete Complaint");
        deleteComplaintBtn.addActionListener(this::deleteComplaintBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1)
                        .addContainerGap(135, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addComplaintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteComplaintBtn)
                        .addGap(37, 37, 37))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addComplaintBtn)
                    .addComponent(deleteComplaintBtn))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addComplaintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComplaintBtnActionPerformed
        // TODO add your handling code here:
        new AddComplaintFrame(currentEmail).setVisible(true);
    }//GEN-LAST:event_addComplaintBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new ResidentDashboard(currentEmail).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void deleteComplaintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteComplaintBtnActionPerformed
        // TODO add your handling code here:
    

    int row = complaintTable.getSelectedRow();

    if(row == -1) {
        JOptionPane.showMessageDialog(this, "Select complaint first");
        return;
    }

int complaintId = Integer.parseInt(complaintTable.getValueAt(row, 0).toString());
    int confirm = JOptionPane.showConfirmDialog(this,
            "Delete this complaint?",
            "Confirm",
            JOptionPane.YES_NO_OPTION);

    if(confirm == JOptionPane.YES_OPTION) {

        dao.UserDAO.deleteComplaint(complaintId, currentEmail);

        JOptionPane.showMessageDialog(this, "Complaint Deleted");

        loadComplaints(currentEmail); // 🔥 FIX
    }


    }//GEN-LAST:event_deleteComplaintBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MyComplaintsFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComplaintBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable complaintTable;
    private javax.swing.JButton deleteComplaintBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
