/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class ResidentDashboard extends javax.swing.JFrame {

    String currentEmail;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ResidentDashboard.class.getName());

    /**
     * Creates new form DashboardFrame
     */
    public ResidentDashboard(String email) {
        initComponents();

        String name = dao.UserDAO.getUserName(email);
        jLabel1.setText("Welcome " + name);

        loadUserDetails(email);
        this.currentEmail = email;
    }

    public void loadUserDetails(String email) {
        try {
            ResultSet rs = dao.UserDAO.getUserDetails(email);

            if (rs.next()) {
                nameLabel.setText(rs.getString("name"));
                emailLabel.setText(rs.getString("email"));
                phoneLabel.setText(rs.getString("phone"));
                blockLabel.setText(rs.getString("block"));
                flatNoLabel.setText(rs.getString("flat_number"));
                typeLabel.setText(rs.getString("type"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        blockLabel = new javax.swing.JLabel();
        flatNoLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        updateProfileBtn = new javax.swing.JButton();
        changePasswordBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome to Dashboard");

        jButton2.setText("My Complaints");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);

        nameLabel.setText("Name");

        emailLabel.setText("Email");

        phoneLabel.setText("Phone");

        blockLabel.setText("Block");

        flatNoLabel.setText("Flat");

        typeLabel.setText("Type");

        jLabel2.setText("Name :");

        jLabel3.setText("Email :");

        jLabel4.setText("Phone :");

        jLabel5.setText("Block :");

        jLabel6.setText("Flat :");

        jLabel7.setText("Type :");

        updateProfileBtn.setText("Update Profile");
        updateProfileBtn.addActionListener(this::updateProfileBtnActionPerformed);

        changePasswordBtn.setText("Change Password");
        changePasswordBtn.addActionListener(this::changePasswordBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58)
                        .addComponent(logoutBtn)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(typeLabel)
                                            .addComponent(flatNoLabel)
                                            .addComponent(blockLabel)
                                            .addComponent(phoneLabel)
                                            .addComponent(emailLabel)
                                            .addComponent(nameLabel))
                                        .addGap(3, 3, 3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(updateProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)))
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(logoutBtn))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blockLabel)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flatNoLabel)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(jLabel7))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(changePasswordBtn))
                .addGap(18, 18, 18)
                .addComponent(updateProfileBtn)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new MyComplaintsFrame(currentEmail).setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void updateProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileBtnActionPerformed
        // TODO add your handling code here:
  

    try {
        ResultSet rs = dao.UserDAO.getUserByEmail(currentEmail);

        if(rs.next()) {

            int userId = rs.getInt("user_id");

            String currentName = rs.getString("name");
            String currentPhone = rs.getString("phone");
            String currentEmailDB = rs.getString("email");

            String newName = JOptionPane.showInputDialog(this, "Enter name", currentName);
            String newPhone = JOptionPane.showInputDialog(this, "Enter phone", currentPhone);
            String newEmail = JOptionPane.showInputDialog(this, "Enter email", currentEmailDB);

            if(newName == null || newPhone == null || newEmail == null) return;

            if(!newName.matches("[A-Za-z ]+")) {
                JOptionPane.showMessageDialog(this, "Invalid name");
                return;
            }

            if(!newPhone.matches("\\d{10}")) {
                JOptionPane.showMessageDialog(this, "Invalid phone");
                return;
            }

            if(!newEmail.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
                JOptionPane.showMessageDialog(this, "Invalid email");
                return;
            }

            dao.UserDAO.updateUser(userId, newName, newPhone);
            dao.UserDAO.updateEmail(userId, newEmail);

            JOptionPane.showMessageDialog(this, "Profile Updated");

        }

    } catch(Exception e) {
        e.printStackTrace();
    }


    }//GEN-LAST:event_updateProfileBtnActionPerformed

    private void changePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordBtnActionPerformed
        // TODO add your handling code here:
        String oldPassword = JOptionPane.showInputDialog(this, "Enter old password");
String newPassword = JOptionPane.showInputDialog(this, "Enter new password");

if(oldPassword == null || newPassword == null) return;

if(newPassword.length() < 6) {
    JOptionPane.showMessageDialog(this, "Password must be at least 6 characters");
    return;
}

try {
    ResultSet rs = dao.UserDAO.getUserByEmail(currentEmail);

    if(rs.next()) {
        int userId = rs.getInt("user_id");
        String actualPassword = rs.getString("password");

        // 🔥 CHECK OLD PASSWORD
        if(!oldPassword.equals(actualPassword)) {
            JOptionPane.showMessageDialog(this, "Old password is incorrect");
            return;
        }

        dao.UserDAO.updatePassword(userId, newPassword);

        JOptionPane.showMessageDialog(this, "Password Updated");
    }

} catch(Exception e) {
    e.printStackTrace();
}
    }//GEN-LAST:event_changePasswordBtnActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                logger.log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(() -> new ResidentDashboard("admin@gmail.com").setVisible(true));
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blockLabel;
    private javax.swing.JButton changePasswordBtn;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel flatNoLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JButton updateProfileBtn;
    // End of variables declaration//GEN-END:variables
}
